[build]
  publish = "_site"
  command = "jekyll build"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[template]
  incoming-hooks = ["Content Management"]

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
